export const characters = [
  {
    id: 'ryu',
    name: 'RYU',
    nameJa: 'リュウ',
    country: 'Japan',
    style: 'Ansatsuken',
    type: 'Shoto',
    difficulty: '1',
    portrait: '/portraits/ryu.png',
    objectPosition: 'center 16%',
    tagline: 'The answer lies in the heart of battle.',
    bio: '世界を旅しながら強者と拳を交える武道家。波動と殺意のあいだで、なお真の強さを探し続けている。',
    moves: ['波動拳', '昇龍拳', '竜巻旋風脚', '電刃波動拳'],
  },
  {
    id: 'chun-li',
    name: 'CHUN-LI',
    nameJa: '春麗',
    country: 'China',
    style: 'Chinese Martial Arts',
    type: 'Footsies',
    difficulty: '2',
    portrait: '/portraits/chunli.png',
    objectPosition: 'center 10%',
    tagline: 'I am the strongest woman in the world.',
    bio: 'ICPO捜査官であり、世界最強を自負する格闘家。正義と家族への想いを胸に、戦場へ立つ。',
    moves: ['百裂脚', '気功拳', '天昇脚', '昇龍天翔脚'],
  },
  {
    id: 'ken',
    name: 'KEN',
    nameJa: 'ケン',
    country: 'U.S.A.',
    style: 'Ansatsuken / Spectacle',
    type: 'Rushdown',
    difficulty: '2',
    portrait: '/portraits/ken.png',
    objectPosition: 'center 14%',
    tagline: 'Now you\'ve made me mad!',
    bio: '炎を纏う攻めが持ち味のアメリカの格闘家。家族と誇りを守りながら、華やかなコンボで試合を支配する。',
    moves: ['波動拳', '昇龍拳', '竜巻旋風脚', '疾風迅雷脚'],
  },
  {
    id: 'juri',
    name: 'JURI',
    nameJa: 'ジュリ',
    country: 'South Korea',
    style: 'Taekwondo',
    type: 'Mix-up',
    difficulty: '3',
    portrait: '/portraits/juri.png',
    objectPosition: 'center 8%',
    tagline: 'Shall we play?',
    bio: '相手をいたぶることを楽しむファイター。風水エンジンを駆り、予測不能なリズムで崩してくる。',
    moves: ['風水エンジン', '炎獄殺', '閃攻脚', '死獄殺'],
  },
  {
    id: 'cammy',
    name: 'CAMMY',
    nameJa: 'キャミィ',
    country: 'United Kingdom',
    style: 'Shadaloo / Delta Red',
    type: 'Rushdown',
    difficulty: '2',
    portrait: '/portraits/cammy.png',
    objectPosition: 'center 12%',
    tagline: 'I will finish this quickly.',
    bio: '元デルタレッドの精鋭。素早い足技と低い姿勢から一気に間合いを詰め、冷静に試合を終わらせる。',
    moves: ['スパイラルアロー', 'キャノンスパイク', 'ホウリング', 'デルタリッド'],
  },
  {
    id: 'luke',
    name: 'LUKE',
    nameJa: 'ルーク',
    country: 'U.S.A.',
    style: 'Military MMA',
    type: 'Pressure',
    difficulty: '1',
    portrait: '/portraits/luke.png',
    objectPosition: 'center 14%',
    tagline: 'Let\'s go! Next generation!',
    bio: '次世代を担う軍人上がりのファイター。ストレートな拳とサンドバッグドライブで、正面から道を切り開く。',
    moves: ['フラッシュナックル', 'サンドバッグ', 'パニッシャースピン', 'パーフェクトウェイクアップ'],
  },
  {
    id: 'jamie',
    name: 'JAMIE',
    nameJa: 'ジェイミー',
    country: 'Hong Kong',
    style: 'Drunken Fist',
    type: 'Charge / Resource',
    difficulty: '4',
    portrait: '/portraits/jamie.png',
    objectPosition: 'center 12%',
    tagline: 'The more I drink, the stronger I get.',
    bio: '酔拳を操るチャイナタウンの若者。飲み進めるほどに動きが変わり、リズムごと相手を翻弄する。',
    moves: ['飲', '破', '酔拳', '百裂酔拳'],
  },
  {
    id: 'kimberly',
    name: 'KIMBERLY',
    nameJa: 'キンバリー',
    country: 'U.S.A.',
    style: 'Bushin-ryu Ninjutsu',
    type: 'Setplay',
    difficulty: '3',
    portrait: '/portraits/kimberly.png',
    objectPosition: 'center 10%',
    tagline: 'Bushin-ryu is the future!',
    bio: '現代に忍術を持ち込む陽気な忍者。スプレーと速度で画面を塗り、セットプレイから一気に畳みかける。',
    moves: ['忍法・移動術', '忍法・天羅地網', 'Bushin Ninjastar', '忍法・爆炎'],
  },
]

export function getCharacter(id) {
  return characters.find((character) => character.id === id) ?? null
}